version: "3.7"

services:
  react_app_init:
    image: ${DOCKER_INTERNAL_REGISTRY:?Registry var unset (see 'Private Docker Registry' in example.env)}/dmod_react_init:${DMOD_REACT_VERSION:-latest}
    build:
      context: ../..
      dockerfile: ./docker/nwm_gui/react_spa/Dockerfile
      target: create_app
      args:
        NODE_VERSION: ${DMOD_REACT_NPM_VERSION:-18}
        REACT_APP_NAME: ${DMOD_REACT_APP_NAME:-dmod_react}

  react_app_dev:
    image: ${DOCKER_INTERNAL_REGISTRY:?Registry var unset (see 'Private Docker Registry' in example.env)}/dmod_react_dev:${DMOD_REACT_VERSION:-latest}
    build:
      context: ../..
      dockerfile: ./docker/nwm_gui/react_spa/Dockerfile
      target: react_dev
      args:
        NODE_VERSION: ${DMOD_REACT_NPM_VERSION:-18}
        REACT_APP_NAME: ${DMOD_REACT_APP_NAME:-dmod_react}

  react_app_local_dev:
    image: ${DOCKER_INTERNAL_REGISTRY:?Registry var unset (see 'Private Docker Registry' in example.env)}/dmod_react_local_dev:${DMOD_REACT_VERSION:-latest}
    build:
      context: ../..
      dockerfile: ./docker/nwm_gui/react_spa/Dockerfile
      target: react_local_dev
      args:
        NODE_VERSION: ${DMOD_REACT_NPM_VERSION:-18}
        REACT_APP_NAME: ${DMOD_REACT_APP_NAME:-dmod_react}

  react_app_prod:
    image: ${DOCKER_INTERNAL_REGISTRY:?Registry var unset (see 'Private Docker Registry' in example.env)}/dmod_react_prod:${DMOD_REACT_VERSION:-latest}
    build:
      context: ../..
      dockerfile: ./docker/nwm_gui/react_spa/Dockerfile
      args:
        NODE_VERSION: ${DMOD_REACT_NPM_VERSION:-18}
        REACT_APP_NAME: ${DMOD_REACT_APP_NAME:-dmod_react}

  # Define a container belonging exclusively to our django application
  app_server:
    image: ${DOCKER_INTERNAL_REGISTRY:?Registry var unset (see 'Private Docker Registry' in example.env)}/dmod-portal-dev:${GUI_PY_APP_IMG_VER:-latest}
    build:
      context: ../..
      dockerfile: ./docker/nwm_gui/app_server/Dockerfile
      args:
        docker_internal_registry: ${DOCKER_INTERNAL_REGISTRY:?Missing DOCKER_INTERNAL_REGISTRY value (see 'Private Docker Registry ' section in example.env)}
        comms_package_name: ${PYTHON_PACKAGE_DIST_NAME_COMMS:?}

networks:
  request-listener-net:
    external: true
    name: ${DOCKER_REQUESTS_NET_NAME}
